document.write('My name is=\"Turki\"')
document.write('</br>')
var name = 'Turki';
document.writeln(name.length)
document.write('</br>')
document.writeln(name.indexOf("r"))
document.write('</br>')
document.writeln(name.toUpperCase())
document.write('</br>')
document.writeln(name.toLowerCase())
